### ISSUE TITLE
Allow working without webfinger

### ISSUE THREAD

**Issue by singpolyma** [mwt/apfollow#1]
By providing the profile URL or id directly.

**Comment by mwt** [comment]
There are two types of people who use this:
- Users who want to be followed, and
- Followers who want to follow users.

Both currently have to support webfinger.

I can allow users to bypass webfinger on the user's instance in the way that you said. I don't know any alternative to webfinger for followers.

I'm unclear on the use case. Do some instances not support webfinger or is this for efficiency?

**Comment by singpolyma** [comment]
Yes, looking at how things are implemented out there I see that webfinger is likely needed for followers.  That's fine, I meant for followees.  Especially for some announce-only stuff when handrolling it can be easier to avoid webfinger, so it would be nice if it worked without that.

**Comment by mwt** [comment]
This is live now. It works with a new `href` query parameter:

https://apfollow.mwt.me/?href=https://mathstodon.xyz/@mwt

This isn't yet documented.
