### ISSUE TITLE
Follow fails with "You don't have permission to view this page."

### ISSUE THREAD

**Issue by donnchawp** [mwt/apfollow#3]
I get almost all the way through the follow process but on the final "Follow" step at https://example.com/authorize_interaction my Mastodon server reports, "You don't have permission to view this page."

Maybe that system is disabled on the server, I'll ask, but I wanted you to be aware of this.

**Comment by mwt** [comment]
Thank you for the report. It works on the mastodon servers that I am on. So, I'm hopeful that this is a configuration issue with this particular mastodon server.

**Comment by mwt** [comment]
@donnchawp is this still an issue?
