### ISSUE TITLE
Follow redirects during webfinger lookup

### ISSUE THREAD

**Issue by snarfed** [mwt/apfollow#6]
Looks like the curl webfinger lookup here doesn't follow redirects:

https://github.com/mwt/apfollow/blob/0c806a9740b50ba613f5ab0fef4c5a72591b2f5d/index.php#L23-L28

...which means it doesn't support addresses like eg @snarfed.org@snarfed.org, since https://snarfed.org/.well-known/webfinger redirects once before it returns the JSON response. Mind adding the `CURL_OPT_...` equivalent of `-L` to make your lookup follow redirects?

**Comment by mwt** [comment]
This is a good idea. I originally didn't support this because I think everything will break (as-is) if you redirect across domains.

Within domain redirects are fine though.

**Comment by snarfed** [comment]
Oh, no, you do want cross-domain redirects. That's the core of what https://fed.brid.gy/ does: adds AP support to existing web sites on their own domain.

For example, https://snarfed.org/.well-known/webfinger?resource=acct:snarfed.org@snarfed.org redirects to https://fed.brid.gy/.well-known/webfinger?resource=acct:snarfed.org@snarfed.org , which serves the Webfinger response data. Background: https://fed.brid.gy/docs

**Comment by mwt** [comment]
Oh, I meant that it would break if the user specifies the wrong handle which redirects to the right domain (because I blindly use the user-provided handle).

If the handle is correct and there is a redirect, then everything should be fine.

**Comment by mwt** [comment]
@snarfed it should be working now:
https://apfollow.mwt.me/?user=snarfed.org&instance=snarfed.org
